<a href="https://colab.research.google.com/github/satyhim/Python_Basic2/blob/main/7_Python_Basic_Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is NumPy

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.

**There are the following advantages of using NumPy for data analysis.**

1)NumPy performs array-oriented computing.

2)It efficiently implements the multidimensional arrays.

3)It performs scientific computations.

4)It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.

5)NumPy provides the in-built functions for linear algebra and random number generation.

#NumPy Ndarray

Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing. Each element of the Array object contains the same size in the memory.

#Creating a ndarray object

The ndarray object can be created by using the array routine of the numpy module. For this purpose, we need to import the numpy.

In [ ]:
import numpy as np
a = np.array
print(a)

<built-in function array>


In [ ]:
# To create an array using the list, use the following syntax.
a = np.array([1, 2, 3])  
a

array([1, 2, 3])

In [ ]:
a = np.array[1, 2, 3]  
a

TypeError: ignored

In [ ]:
# To create a multi-dimensional array object, use the following syntax.
a = np.array([[1, 2, 3], [4, 5, 6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# To change the data type of the array elements, mention the name of the data type along with the collection.
a = np.array([1, 3, 5, 7], complex)  
a

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j])

In [ ]:
a = np.array([[1, 3, 5, 7],complex,[4,5,6], complex])  
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 3, 5, 7]), <class 'complex'>, list([4, 5, 6]),
       <class 'complex'>], dtype=object)

#Finding the dimensions of the Array

The ndim function can be used to find the dimensions of the array.

In [ ]:
import numpy as np  
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])  
  
print(arr.ndim)

2


In [ ]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])  
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 23]])

#Finding the size of each array element

The itemsize function is used to get the size of each array item. It returns the number of bytes taken by each array element.

Consider the following example.

In [ ]:
#finding the size of each item in the array  
import numpy as np  
a = np.array([[1,2,3]])  
print("Each item contains",a.itemsize,"bytes")e